import Head from 'next/head';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { isLoggedIn } from '@/utils/auth';
import { useRouter } from 'next/router';
import { DASHBOARD_ROUTE } from '@/constants/routes';
import { useEffect } from 'react';

const Home = () => {
  const isAuthenticated = isLoggedIn();
  const router = useRouter();

  useEffect(() => {
    if (isAuthenticated) {
      router.push(DASHBOARD_ROUTE);
    }
  }, [isAuthenticated]);

  return (
    <>
      <Head>
        <title>Yust Infra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
